# .github/workflows/update-epg.yml

name: Update SPFL EPG

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update fixture data
        env:
          SPORTMONKS_API_TOKEN: ${{ secrets.SPORTMONKS_API_TOKEN }}
        run: |
          python data_layer.py

      - name: Generate XMLTV
        run: |
          python generator.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./output

      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
